name: 🚀 Deploy website on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
        
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{ secrets.SERVER }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            local-dir: './api/'
            server-dir: './public_html/'